### ISSUE TITLE
Crash when open example ElstobD-Regular.yaml

### ISSUE THREAD

**Issue by navv-1** [psb1558/ygt#5]
Can't open example on win10 and got this error:
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\ygt\window.py", line 1120, in open_file
    result = self._open(f)
  File "C:\Python310\lib\site-packages\ygt\window.py", line 1294, in _open
    modelGlyph = ygGlyph(self.preferences, self.yg_font, initGlyph)
  File "C:\Python310\lib\site-packages\ygt\ygModel.py", line 2149, in __init__
    self._yaml_supply_refs(self.current_block())
  File "C:\Python310\lib\site-packages\ygt\ygModel.py", line 2294, in _yaml_supply_refs
    self._yaml_supply_refs(n["points"])
  File "C:\Python310\lib\site-packages\ygt\ygModel.py", line 2277, in _yaml_supply_refs
    type_num = hint_type_nums[self._yaml_hint_type(n)]
KeyError: 'blackspace'

**Comment by psb1558** [comment]
Sorry, my fault. I recently changed the names of some hint types: blackspace -> blackdist, whitespace -> whitedist, grayspace -> graydist. This fixed an inconsistency. I changed the documentation and the example file, but didn't think that there would be old copies of the example file around.

I've added a few lines that silently make the changes when loading a glyph. This fix is in the repository now, and I'll put a new version on PyPi later today.
